### ISSUE TITLE
K8s/Deployment: Formatting progress show

### ISSUE THREAD

**Issue by caoxianfei1** [opencurve/curve-operator#30]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Curve may wait for a long time when executing format to generate chunkfilepool. We can display the current formatting progress in the status field of cluster crd, which is user-friendly.

**Describe the solution you'd like (描述你期望的解决方法)**

It may display as follows under the status field

```yaml
  status:
    conditions:
    - lastTransitionTime: "2023-04-04T10:58:21Z"
      ...
    - lastTransitionTime: "2023-04-04T10:58:41Z"
      ...
    - lastTransitionTime: "2023-04-04T10:58:41Z"
      message: Formating chunkfilepool
      reason: FormatingChunkfilePool
      status: "True"
      type: formating
      # Add a line here or another
      progress: 70
    curveVersion:
      image: opencurvedocker/curvebs:v1.2
    message: Formating chunkfilepool
    phase: Pending
```
